version: "3.7"
services:
  spark-master:
    image: spark-master:2.3.1
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker-1:
    image: spark-worker:2.3.1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"

    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
